Traceback (most recent call last):
  File "test/verify/check-connection", line *, in testSocket
*
AssertionError: '9090' unexpectedly found in 'Web console: https://localhost:9090/\n\n'
