Traceback (most recent call last):
  File "check-multi-machine", line 404, in testTroubleshooting
    m1.execute("semanage port -a -t ssh_port_t -p tcp 2222")
